### ISSUE TITLE
When will the paper and code be released?

### ISSUE THREAD

**Issue by isxuwl** [MKMaS-GUET/KuDA#2]
Knowledge-Guided Dynamic Modality Attention Fusion Framework for Multimodal Sentiment Analysis
Xinyu Feng, Yuming Lin, Lihua He, You Li, Liang Chang, Ya Zhou

**Comment by xyFeng-guet** [comment]
We are honored that you are interested in our work. The paper has been published on Arxiv. However, since the code needs to be organized, it will be published later. Thank you for your attention.😄

**Comment by huigeStudent** [comment]
When will the paper and code be released? thanks

**Comment by xyFeng-guet** [comment]
Welcome to follow our work; the paper is now available for download at EMNLP2024. The initial version of the code has been updated in the corresponding repository (due to the different parameters of each dataset, adjustments are required during runtime). If you have any questions, you are welcome to communicate with us. Thanks! 🎉
